# Отчет по лабораторной работе 1.1
**Тема:** Базовая настройка, ARP, статическая маршрутизация  
**Выполнили:** Родионов Р.А Шаталова В.А, гр. 539  

## Часть 1: Создание топологии и начальная конфигурация устройств

### Шаг 1

Собрали схему в Packet Tracer и соединили устройства по таблице портов.
![Топология сети](figures/image-1.png)

Настроили статические IP-адреса, маски и шлюзы на компьютерах `PC0`, `PC1` и `PC2`.

![Настройки IP на PC0](figures/image-2.png)  
![Настройки IP на PC1](figures/image-3.png)  
![Настройки IP на PC2](figures/image-4.png)  

Через консоль выполнили базовую настройку `R1`, `R2` и `SW1` (задали hostname, пароли, шифрование, параметры консоли и IP на интерфейсах), после чего сохранили конфиг.

```
SW1#show running-config 
Building configuration...

Current configuration : 1316 bytes
!
version 15.0
no service timestamps log datetime msec
no service timestamps debug datetime msec
service password-encryption
!
hostname SW1
!
enable secret 5 $1$mERr$hx5rVt7rPNoS4wqbXKX7m0
!
!
!
no ip domain-lookup
!
username admin secret 5 $1$mERr$hx5rVt7rPNoS4wqbXKX7m0
!
!
!
spanning-tree mode pvst
spanning-tree extend system-id
!
interface FastEthernet0/1
!
interface FastEthernet0/2
!
interface FastEthernet0/3
!
interface FastEthernet0/4
!
interface FastEthernet0/5
!
interface FastEthernet0/6
!
interface FastEthernet0/7
!
interface FastEthernet0/8
!
interface FastEthernet0/9
!
interface FastEthernet0/10
!
interface FastEthernet0/11
!
interface FastEthernet0/12
!
interface FastEthernet0/13
!
interface FastEthernet0/14
!
interface FastEthernet0/15
!
interface FastEthernet0/16
!
interface FastEthernet0/17
!
interface FastEthernet0/18
!
interface FastEthernet0/19
!
interface FastEthernet0/20
!
interface FastEthernet0/21
!
interface FastEthernet0/22
!
interface FastEthernet0/23
!
interface FastEthernet0/24
!
interface GigabitEthernet0/1
!
interface GigabitEthernet0/2
!
interface Vlan1
 description MGMT
 ip address 192.168.10.254 255.255.255.0
!
ip default-gateway 192.168.10.1
!
!
!
!
line con 0
 logging synchronous
 login local
 speed 115200
!
line vty 0 4
 login
line vty 5 15
 login
!
!
!
!
end
```
```
R1#show running-config 
Building configuration...

Current configuration : 982 bytes
!
version 15.1
no service timestamps log datetime msec
no service timestamps debug datetime msec
service password-encryption
!
hostname R1
!
!
!
enable secret 5 $1$mERr$hx5rVt7rPNoS4wqbXKX7m0
!
!
!
!
!
!
ip cef
no ipv6 cef
!
!
!
username admin privilege 15 secret 5 $1$mERr$hx5rVt7rPNoS4wqbXKX7m0
!
!
license udi pid CISCO2911/K9 sn FTX1524VN05-
!
!
!
!
!
!
!
!
!
no ip domain-lookup
!
!
spanning-tree mode pvst
!
!
!
!
!
!
interface GigabitEthernet0/0
 description LAN1
 ip address 192.168.10.1 255.255.255.0
 duplex auto
 speed auto
!
interface GigabitEthernet0/1
 description LAN2
 ip address 192.168.20.1 255.255.255.128
 duplex auto
 speed auto
!
interface GigabitEthernet0/2
 description UPLINK
 ip address 10.10.12.2 255.255.255.252
 duplex auto
 speed auto
!
interface Vlan1
 no ip address
 shutdown
!
ip classless
!
ip flow-export version 9
!
!
!
no cdp run
!
!
!
!
!
line con 0
 speed 115200
 logging synchronous
 login local
!
line aux 0
!
line vty 0 4
 login
!
!
!
end
```
R2#show runn
R2#show running-config 
Building configuration...

Current configuration : 934 bytes
!
version 15.1
no service timestamps log datetime msec
no service timestamps debug datetime msec
service password-encryption
!
hostname R2
!
!
!
enable secret 5 $1$mERr$hx5rVt7rPNoS4wqbXKX7m0
!
!
!
!
!
!
ip cef
no ipv6 cef
!
!
!
username admin privilege 15 secret 5 $1$mERr$hx5rVt7rPNoS4wqbXKX7m0
!
!
license udi pid CISCO2911/K9 sn FTX1524ZULZ-
!
!
!
!
!
!
!
!
!
no ip domain-lookup
!
!
spanning-tree mode pvst
!
!
!
!
!
!
interface GigabitEthernet0/0
 description ISP1
 no ip address
 duplex auto
 speed auto
!
interface GigabitEthernet0/1
 description ISP2
 no ip address
 duplex auto
 speed auto
!
interface GigabitEthernet0/2
 description DOWNLINK
 ip address 10.10.12.1 255.255.255.252
 duplex auto
 speed auto
!
interface Vlan1
 no ip address
 shutdown
!
ip classless
!
ip flow-export version 9
!
!
!
no cdp run
!
!
!
!
!
line con 0
 speed 115200
 logging synchronous
 login local
!
line aux 0
!
line vty 0 4
 login
!
!
!
end
```
### Шаг 2
```
Проверили доступность узлов командой `ping` с `PC0` до `PC1` и `PC2`. Посмотрели таблицы MAC на `SW1` и ARP на `PC0` и `R1`
```
C:\>ping 192.168.20.102

Pinging 192.168.20.102 with 32 bytes of data:

Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 192.168.20.102:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

C:\>ping 192.168.10.101

Pinging 192.168.10.101 with 32 bytes of data:

Reply from 192.168.10.101: bytes=32 time<1ms TTL=128
Reply from 192.168.10.101: bytes=32 time<1ms TTL=128
Reply from 192.168.10.101: bytes=32 time<1ms TTL=128
Reply from 192.168.10.101: bytes=32 time<1ms TTL=128

Ping statistics for 192.168.10.101:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```
```
arp -a
  Internet Address      Physical Address      Type
  192.168.10.1          0001.961b.0001        dynamic
  192.168.10.101        0060.2f67.19d9        dynamic
  ```
  ```
  `R1#show ar
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  10.10.12.2              -   0001.961B.0003  ARPA   GigabitEthernet0/2
Internet  192.168.10.1            -   0001.961B.0001  ARPA   GigabitEthernet0/0
Internet  192.168.10.100          35  0005.5ED6.586D  ARPA   GigabitEthernet0/0
Internet  192.168.20.1            -   0001.961B.0002  ARPA   GigabitEthernet0/1
Internet  192.168.20.102          35  0001.43E7.2596  ARPA   GigabitEthernet0/1``
  ```
**Ответы на вопросы:**
1. [эхо-запросы pc0-pc1 проходят успешно. эхо запросы PC0-PC2 не проходят, у PC2 и R1 разные маски]
2. [h]
3. [в ARP таблицих]

## Часть 2: Роль IP и MAC адреса при прямой и косвенной пересылке

### Шаг 1

Перешли в режим симуляции, настроили фильтр на протокол `ICMP` и отправили пинг с `PC0` на `PC2`.

![Фильтр ICMP в симуляции](figures/image-5.png)

### Шаг 2

Открыли пакет на `PC0` и изучили заголовки.

![Пакет на PC0](figures/image-6.png)

* **DEST MAC:** [Указать, чей MAC-адрес указан в кадре и объяснить, почему]

Прогнали симуляцию до `R1` и посмотрели `Outbound PDU Details`.

![Исходящий пакет на R1](figures/image-7.png)

* **SRC и DEST MAC:** [Указать адреса и объяснить, почему они изменились]